cc_test(
  name = "tensor_test",
  srcs = ["tensor_test.cc"],
  deps = ["//core:tensorlib", "@com_google_googletest//:gtest_main"],
)

cc_test(
  name = "accessor_test",
  srcs = ["accessor_test.cc"],
  deps = ["//core:tensorlib", "@com_google_googletest//:gtest_main"],
)
