load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "tensorlib",
    srcs = ["storage.cc", "tensor.cc"],
    hdrs = ["storage.h", "tensor.h"],
    visibility = ["//visibility:public"]
)
